version: '2'
volumes:
    database: {}
services:
  ksmppd:
    hostname: ksmppd
    build: .
    ports:
      - "2345:2345"
      - "14010:14010"
    volumes:
      - ./config:/etc/kannel
    depends_on:
      - bearerbox
      - mariadb
    entrypoint:
      - /wait-for-it.sh
    command: [
      "mariadb:3306", "--",
      "/usr/local/bin/ksmppd", "/etc/kannel/ksmppd.conf"
    ]
  mariadb:
    image: mariadb
    environment:
     - MYSQL_RANDOM_ROOT_PASSWORD=yes
     - MYSQL_DATABASE=ksmppd
    volumes:
     - ./initdb:/docker-entrypoint-initdb.d
     - database:/var/lib/mysql
  bearerbox:
    image: onlinecity/kannel
    hostname: bearerbox
    entrypoint: bearerbox
    command: /etc/kannel/kannel.conf
    volumes:
      - ./config:/etc/kannel
      - ./log:/var/log/kannel
  smsbox:
    image: onlinecity/kannel
    hostname: smsbox
    entrypoint: smsbox
    command: /etc/kannel/kannel.conf
    ports:
      - "14013:14013"
    links:
      - bearerbox
    volumes:
      - ./config:/etc/kannel
      - ./log:/var/log/kannel
